import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { CashMovementType, Prisma } from '@prisma/client';
import { AuthenticatedUser } from '../auth/auth.types';
import { PrismaService } from '../prisma/prisma.service';
import { OpenCashSessionDto } from './dto/open-cash-session.dto';
import { CreateCashMovementDto } from './dto/create-cash-movement.dto';
import { CloseCashSessionDto } from './dto/close-cash-session.dto';
@Injectable()
export class CashService {
  constructor(private readonly prisma: PrismaService) {}
  async overview(user: AuthenticatedUser, branchId?: string) { const selectedBranchId = this.authorizedBranch(user, branchId); const [registers, openSession, recentSessions] = await Promise.all([this.prisma.cashRegister.findMany({ where: { branchId: selectedBranchId, active: true }, orderBy: { name: 'asc' } }), this.prisma.cashSession.findFirst({ where: { status: 'OPEN', cashRegister: { branchId: selectedBranchId } }, include: { cashRegister: true, movements: { orderBy: { createdAt: 'desc' } }, invoices: { where: { status: { in: ['PAID', 'PARTIALLY_RETURNED', 'FULLY_RETURNED'] } }, select: { id: true, number: true, total: true, changeAmount: true, createdAt: true } } }, orderBy: { openedAt: 'desc' } }), this.prisma.cashSession.findMany({ where: { cashRegister: { branchId: selectedBranchId }, status: { not: 'OPEN' } }, include: { cashRegister: true }, orderBy: { openedAt: 'desc' }, take: 20 })]); return { registers, openSession: openSession ? { ...openSession, expectedCash: this.expected(openSession.openingAmount, openSession.movements) } : null, recentSessions }; }
  async open(user: AuthenticatedUser, dto: OpenCashSessionDto) { const register = await this.prisma.cashRegister.findFirst({ where: { id: dto.cashRegisterId, active: true, branch: { businessId: user.businessId, users: { some: { userId: user.id } } } } }); if (!register) throw new NotFoundException('Caja registradora no disponible.'); const existing = await this.prisma.cashSession.findFirst({ where: { cashRegisterId: register.id, status: 'OPEN' } }); if (existing) throw new BadRequestException('Esta caja ya tiene una sesión abierta.'); const session = await this.prisma.cashSession.create({ data: { cashRegisterId: register.id, openedById: user.id, openingAmount: dto.openingAmount } }); await this.audit(user, 'CASH_SESSION_OPENED', 'CashSession', session.id, dto); return session; }
  async movement(user: AuthenticatedUser, sessionId: string, dto: CreateCashMovementDto) { const manualTypes = new Set<CashMovementType>([CashMovementType.INCOME, CashMovementType.WITHDRAWAL, CashMovementType.EXPENSE, CashMovementType.ADJUSTMENT]); if (!manualTypes.has(dto.type)) throw new BadRequestException('Tipo de movimiento manual no permitido.'); const withdrawalTypes = new Set<CashMovementType>([CashMovementType.WITHDRAWAL, CashMovementType.EXPENSE]); if (withdrawalTypes.has(dto.type) && !user.permissions.includes('cash.withdrawals')) throw new ForbiddenException('No tiene permiso para retiros o gastos.'); const session = await this.openSession(user, sessionId); const movement = await this.prisma.cashMovement.create({ data: { cashSessionId: session.id, type: dto.type, amount: dto.amount, reason: dto.reason.trim(), createdById: user.id } }); await this.audit(user, 'CASH_MOVEMENT_CREATED', 'CashMovement', movement.id, dto); return movement; }
  async close(user: AuthenticatedUser, sessionId: string, dto: CloseCashSessionDto) { const session = await this.openSession(user, sessionId); const movements = await this.prisma.cashMovement.findMany({ where: { cashSessionId: session.id } }); const expectedCash = this.expected(session.openingAmount, movements); const difference = Math.round((dto.countedCash - expectedCash) * 100) / 100; const updated = await this.prisma.cashSession.update({ where: { id: session.id }, data: { expectedCash, countedCash: dto.countedCash, difference, status: difference === 0 ? 'CLOSED' : 'WITH_DIFFERENCE', closedAt: new Date(), closedById: user.id } }); await this.audit(user, 'CASH_SESSION_CLOSED', 'CashSession', session.id, { expectedCash, countedCash: dto.countedCash, difference }); return updated; }
  private async openSession(user: AuthenticatedUser, sessionId: string) { const session = await this.prisma.cashSession.findFirst({ where: { id: sessionId, status: 'OPEN', cashRegister: { branch: { businessId: user.businessId } } } }); if (!session) throw new NotFoundException('Sesión de caja abierta no encontrada.'); return session; }
  private expected(openingAmount: Prisma.Decimal | number, movements: Array<{ type: CashMovementType; amount: Prisma.Decimal }>) { const positiveTypes = new Set<CashMovementType>([CashMovementType.SALE_CASH, CashMovementType.INCOME, CashMovementType.ADJUSTMENT]); return Math.round((Number(openingAmount) + movements.reduce((sum, movement) => sum + (positiveTypes.has(movement.type) ? Number(movement.amount) : -Number(movement.amount)), 0)) * 100) / 100; }
  private authorizedBranch(user: AuthenticatedUser, branchId?: string) { const selected = branchId ?? user.branches[0]?.id; if (!selected || !user.branches.some((branch) => branch.id === selected)) throw new ForbiddenException('La sucursal no está autorizada.'); return selected; }
  private audit(user: AuthenticatedUser, action: string, entityType: string, entityId: string, after: unknown) { return this.prisma.auditLog.create({ data: { businessId: user.businessId, userId: user.id, action, entityType, entityId, after: JSON.parse(JSON.stringify(after)) as Prisma.InputJsonValue } }); }
}
